### ISSUE TITLE
consider using Counter

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/json-schema-to-dash-forms#5]
https://github.com/catalystneuro/json-schema-to-dash-forms/blob/ba1f541cf25d6fe54cefe6497af627b5f02500f6/json_schema_to_dash_forms/forms.py#L424-L431

I think this could be cleaner if you used `from collections import Counter`

**Comment by bendichter** [comment]
You also might want to think about using something like

```python
from collections import defaultdict

form_values = defaultdict(list)
for string value in string_values:
    form_values['string].append(string_value)
```

to keep track of the form values. Then you could pass in one `defaultdict` object instead of all listing all of the different data types.

**Comment by vinicvaz** [comment]
I added collections counter to track the current field.
I didn't quite understand the suggestion of defaultdict because we are updating the internal dict matching the form ID to the current form state.
If there is a better way please reopen this issue

**Comment by bendichter** [comment]
I'm a bit confused because it doesn't look like `form.update_internal_dict` is called anywhere

**Comment by vinicvaz** [comment]
Yes, update_internal_dict isnt called explicitly. 
This function is a callback function triggered by an exposed trigger on SchemaFormContainer class.
